#file: noinspection YAMLSchemaValidation
name: Deploy JS target
on: [ push ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '#deploy') }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout-ref || github.ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Code build
        run: ./gradlew browserReleaseEsbuild
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{secrets.SSH_KNOWN_HOSTS_CONTENTS}}
      - name: Deploy with rsync
        run: rsync -avz --del -e "ssh -p ${{ secrets.SSH_SERVER_PORT }}" ./gui/build/www/ ${{ secrets.SSH_SERVER_USER }}@${{ secrets.SSH_SERVER_HOST }}:${{ secrets.SSH_SERVER_RSYNC_PATH }}
